USE EJERCICIO
GO

SELECT DIR FROM CLIENTE WHERE DIR ='APODACA'
SELECT * FROM PROVEEDOR WHERE DIR_PRO ='MONTERREY'
SELECT NOMP, PRECIO  FROM PRODUCTO WHERE PRECIO > 10 
SELECT NOMP FROM PRODUCTO WHERE SUBSTRING(NOMP,1,1)='G'
SELECT TEL FROM CLIENTE WHERE SUBSTRING(APES,1,1)='M'

SELECT COUNT (DIR) FROM CLIENTE WHERE DIR = 'APODACA'
SELECT AVG (PRECIO) FROM PRODUCTO

SELECT NOM FROM CLIENTE GROUP BY NOM HAVING SUBSTRING(NOM,1,1)='A'
SELECT NOM FROM CLIENTE GROUP BY NOM HAVING SUBSTRING(NOM,1,1)='J'
SELECT NOM_PRO FROM PROVEEDOR GROUP BY NOM_PRO HAVING SUBSTRING(NOM_PRO,1,1)='P'
SELECT NOM_PRO FROM PROVEEDOR GROUP BY NOM_PRO,DIR_PRO
SELECT NOM FROM CLIENTE GROUP BY NOM,TEL

SELECT NOM FROM CLIENTE GROUP BY NOM HAVING SUBSTRING(NOM,1,1)='O'
SELECT COD_P FROM COMPRA GROUP BY COD_P HAVING COUNT(COD_P) > 5
SELECT PRECIO FROM PRODUCTO GROUP BY PRECIO HAVING AVG(PRECIO) > 10
SELECT DIR FROM CLIENTE GROUP BY DIR HAVING DIR != 'APODACA'
SELECT DIR_PRO FROM PROVEEDOR GROUP BY DIR_PRO HAVING DIR_PRO = 'MONTERREY'

SELECT * FROM COMPRA
SELECT TOP 5 * FROM CLIENTE WHERE APES = 'MARTINEZ'
SELECT TOP 5 * FROM CLIENTE WHERE DIR = 'SAN NICOLAS'
SELECT TOP 3 * FROM COMPRA WHERE COD_P > 5
SELECT TOP 2 * FROM CLIENTE WHERE DIR = 'ESCOBEDO'
SELECT TOP 4 * FROM PRODUCTO WHERE PRECIO > 10

SELECT * FROM CLIENTE 
INNER JOIN PROVEEDOR 
ON CLIENTE.DIR = PROVEEDOR.DIR_PRO;
SELECT NOM_PRO FROM PROVEEDOR
INNER JOIN PRODUCTO
ON PROVEEDOR.RFC_PRO != PRODUCTO.NOMP

SELECT * FROM CLIENTE 
LEFT JOIN PROVEEDOR 
ON CLIENTE.DIR = PROVEEDOR.DIR_PRO;
SELECT * FROM COMPRA 
LEFT JOIN CLIENTE
ON COMPRA.CURP = CLIENTE.CURP;

SELECT * FROM CLIENTE 
RIGHT JOIN PROVEEDOR 
ON CLIENTE.DIR = PROVEEDOR.DIR_PRO;
SELECT * FROM COMPRA 
RIGHT JOIN PRODUCTO
ON COMPRA.COD_P = PRODUCTO.COD_P;


SELECT * FROM CLIENTE 
CROSS JOIN PROVEEDOR
SELECT * FROM COMPRA 
CROSS JOIN PRODUCTO


SELECT NOMP FROM PRODUCTO

SELECT * FROM COMPRA WHERE CURP = (SELECT CURP FROM CLIENTE where CURP = COMPRA.CURP)



