 CREATE VIEW CLIENTE_DIR
 AS 
 SELECT NOM , DIR FROM CLIENTE GROUP BY NOM , DIR
 GO
 SELECT * FROM CLIENTE_DIR
 
 CREATE VIEW CLIENTE_TEL
 AS
 SELECT NOM , TEL FROM CLIENTE GROUP BY NOM , TEL
 GO
 SELECT * FROM CLIENTE_TEL
 CREATE VIEW 