USE EJERCICIO
GO



CREATE PROCEDURE CLIENTE_DIRP  @NOM NVARCHAR(20) , @DIR NVARCHAR (20)
AS
SELECT NOM FROM CLIENTE_DIR WHERE NOM = @NOM AND DIR = @DIR
GO

GO
CREATE PROCEDURE CLIENTES_A @NOM NVARCHAR(20) AS
SELECT NOM FROM CLENTE_A GROUP BY NOM HAVING SUBSTRING(@NOM,1,1)='A'
GO


CREATE PROCEDURE PRIMERALETRA (@letra as varchar(1)) AS 
BEGIN
	SELECT * FROM personas_compras WHERE SUBSTRING(NOM,1,1)=@letra
END
GO
CREATE PROCEDURE COMPRA_PROD(@codigoProducto as varchar(30)) AS
BEGIN
	SELECT * FROM PROD_COMPRAS WHERE COD_P=(SELECT COD_P FROM PRODUCTO WHERE COD_P=@codigoProducto)
END
GO
DROP PROCEDURE COMPRA_PROD

GO
CREATE PROCEDURE PERSONASPORDIR(@dir as varchar(50)) AS
BEGIN
 SELECT * FROM personas_compras WHERE DIR=@dir
END

GO
CREATE FUNCTION VALIDAR_TEL( @TEL AS INT )
RETURNS VARCHAR (10)
AS
BEGIN
	RETURN CAST(@TEL AS VARCHAR(10)) 
END
go
CREATE FUNCTION EnMinusculas
(
@Nom Varchar(30),
@Apes Varchar(30)
)
RETURNS Varchar(100)
AS
BEGIN
 RETURN (LOWER(@Apes) + ', ' + LOWER(@Nom))
END
GO
CREATE TABLE RESP
(
NOM VARCHAR(30) NOT NULL,
APES VARCHAR(30) NOT NULL,
CURP VARCHAR(18) NOT NULL,
DIR VARCHAR(30) NOT NULL,
TEL INT,
PRIMARY KEY(CURP)
)
GO
CREATE TRIGGER CIENTESB
ON CLIENTE
AFTER DELETE
AS
BEGIN 
	INSERT RESP
	SELECT *
	FROM deleted
END

GO
CREATE TRIGGER PRODin
ON PRODUCTO
INSTEAD of insert
AS
BEGIN 
	insert into PRODUCTO
     select*
     from inserted where PRECIO > 10 
END